require('angular');
require('angular-route');
require('angular-animate');
require('angular-messages');
require('angular-sanitize');
require('angular-touch');
require('ng-storage');
require('ng-cordova');
require('ink.angular');